#!/bin/bash
#BASEDIR=$(dirname $(realpath "$0"));
BASEDIR=$( cd "$(dirname "$0")" ; pwd -P )
export HMHOME=$BASEDIR;
export PYTHONPATH=$BASEDIR;
export PATH=$PATH:$HMHOME/bin;
home(){ echo $BASEDIR; }
list(){ 
	if [ -z $1 ];then
		$0 declare -F | sed 's/declare -f //g' ; 
	else
		$0 declare -f $1 

	fi
}

if [ $# -lt 1 ];then
cat<<-eof
	Hyunmin's Tools
	Version:   v0.1
	Mail:      human.gim@gmail.com 
	Usage:     hm <subcommand> 

	<subcommand> :
eof

else
        for f in $BASEDIR/src/*.sh;do
                . $f
        done
        ${@:1}
fi

